Restore Tribe mention from static file mapping

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,6 +27,10 @@ runs:
         doGetCurl() {
           curl -A "PR Webhook Tasks/1.0" -s -f -L -u ${SERVER_USERNAME}:${SERVER_PASSWORD} -XGET $*
         }
+        getAssociatedTribeAccount() {
+          [ -f /tmp/ghtribe.json ] || return
+          jq -r ".[] | select(.githubid == \"$1\") | .tribeid" /tmp/ghtribe.json
+        }
         if [[ ! ${base_branch_name} =~ ^(master|develop(-exo|-meed)?|feature\/[A-Za-z-]+[0-9]?|stable\/[0-9]+(\.[0-9]+)*\.x)$ ]]; then
           echo "❌ Branch ${base_branch_name} is not supported for Task notification. Abort"
           exit 0
@@ -43,10 +47,17 @@ runs:
         echo "OK Task(s) found! Starting notifications..."
         reducedBaseBranchName=$(echo ${base_branch_name} | sed -e 's|feature/||gi' -e 's|stable/||gi')
         link="PR <a href=\"https://github.com/${full_repo_name}/pull/${pull_number}\" title="${full_repo_name}#${pull_number}:${base_branch_name}" target="_blank">${repo_name}#${pull_number}:${reducedBaseBranchName}</a>"
+        curl -A "PR Webhook Tasks/1.0" -s -f -L "${SERVER_GAMGH_MAPPING_FILE_URL}" > /tmp/ghtribe.json
         if [ "${{ github.event_name }}" = "pull_request" ]; then
           if [ "${{ github.event.action }}" = "review_requested" ]; then
-              echo "Requested reviewer is: ${requested_reviewer}."
-              msg="💭 $link requested a review from <tt>${requested_reviewer}</tt>"
+            serverUser=$(getAssociatedTribeAccount ${requested_reviewer})
+            if [ ! -z "${serverUser}" ]; then
+              echo "Requested reviewer is: ${serverUser}."
+              msg="💭 $link requested a review from @${serverUser} "
+            else
+              echo "❌ Could not get Server user identifier! Abort"
+              exit 0
+            fi
           elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
             shortCommitId=$(echo ${{ github.event.pull_request.merge_commit_sha }} | cut -c1-7)
             mergeMethod="merged"
@@ -56,7 +67,15 @@ runs:
             mergedCommitlink="<a href=\"https://github.com/${full_repo_name}/commit/${{ github.event.pull_request.merge_commit_sha }}\" target="_blank">${shortCommitId}</a>"
             base_branch_link="<a href=\"https://github.com/${full_repo_name}/tree/${base_branch_name}\" target="_blank">${base_branch_name}</a>"
             mergerGithubUser="${{ github.event.pull_request.merged_by.login }}"
-            msg="🌟 $link has <tt>${mergeMethod}</tt> ${mergedCommitlink} into ${base_branch_link} by <tt>${mergerGithubUser}</tt>."
+            mergerServerUser=$(getAssociatedTribeAccount ${mergerGithubUser})
+            mergerServerProfile=$(doGetCurl "${SERVER_URL}/rest/private/v1/social/users/${mergerServerUser}" 2>/dev/null || echo "")
+            mergerServerFullName="$(echo ${mergerServerProfile} | jq -r .fullname)"
+            mergerServerLink="<a target=\"_self\" rel=\"noopener\" href=\"/portal/${SERVER_DEFAULT_SITENAME}/profile/${mergerServerUser}\" class=\"user-suggester\">${mergerServerFullName}</a>"
+            if [ -z "${mergerServerFullName:-}" ] || [ "${mergerServerFullName:-}" = "null" ]; then 
+              msg="🌟 $link has <tt>${mergeMethod}</tt> ${mergedCommitlink} into ${base_branch_link}."
+            else
+              msg="🌟 $link has <tt>${mergeMethod}</tt> ${mergedCommitlink} into ${base_branch_link} by ${mergerServerLink}."
+            fi
           elif [ "${{ github.event.action }}" = "closed" ]; then
             msg="🍂 $link has been <tt>${{ github.event.action }}</tt>."
           elif [ "${{ github.event.action }}" = "opened" ]; then
@@ -67,14 +86,41 @@ runs:
             msg="ℹ️ $link has been <tt>${{ github.event.action }}</tt>."
           fi
         elif [ "${{ github.event_name }}" = "pull_request_review" ] && [ "${{ github.event.action }}" = "submitted" ]; then
+          mentionCreator=""
+          commentMentionFilterRegex='( |^)@[a-zA-Z0-9]+-?[a-zA-Z0-9]+( |$)'
+          response=$(getAssociatedTribeAccount ${creator})
+          [ -z "${response}" ] || mentionCreator=" FYI @${response} "
           reviewerGithubUser="${{ github.event.review.user.login }}"
+          reviewerServerUser=$(getAssociatedTribeAccount ${reviewerGithubUser})
+          reviewerServerProfile=$(doGetCurl "${SERVER_URL}/rest/private/v1/social/users/${reviewerServerUser}" 2>/dev/null || echo "")
+          reviewerServerFullName="$(echo ${reviewerServerProfile} | jq -r .fullname)"
+          reviewerServerLink="<a target=\"_self\" rel=\"noopener\" href=\"/portal/${SERVER_DEFAULT_SITENAME}/profile/${reviewerServerUser}\" class=\"user-suggester\">${reviewerServerFullName}</a>"
           reviewEventLink="${{ github.event.review.html_url }}"
           if [ "${{ github.event.review.state }}" = "changes_requested" ]; then
             requestChangesEventLink="<a href=\"$reviewEventLink\">changes</a>"
-            msg="🛠️ $link requires ${requestChangesEventLink} from <tt>${reviewerGithubUser}</tt>."
+            if [ -z "${reviewerServerFullName:-}" ]; then 
+              msg="🛠️ $link requires ${requestChangesEventLink}.${mentionCreator}"
+            else 
+              msg="🛠️ $link requires ${requestChangesEventLink} from ${reviewerServerLink}.${mentionCreator}"
+            fi
           elif [ "${{ github.event.review.state }}" = "approved" ]; then
             approvedEventLink="<a href=\"$reviewEventLink\">approved</a>"
-            msg="✅ $link has been ${approvedEventLink} by <tt>${reviewerGithubUser}</tt>."
+            if [ -z "${reviewerServerFullName:-}" ]; then 
+              msg="✅ $link has been ${approvedEventLink}.${mentionCreator}"
+            else 
+              msg="✅ $link has been ${approvedEventLink} by ${reviewerServerLink}.${mentionCreator}"
+            fi
+          elif [ "${{ github.event.review.state }}" = "commented" ] && [[ "${{ github.event.review.body }}" =~ $commentMentionFilterRegex ]]; then
+            mentionEventLink="<a href=\"$reviewEventLink\" target="_blank">mentioned</a>"
+            mentionedGithubUsers=$(echo "${{ github.event.review.body }}" | grep -oP "$commentMentionFilterRegex" | tr -d '@' | xargs)
+            mentionedServerUsers=""
+            for mentionedGithubUser in ${mentionedGithubUsers}; do 
+              response=$(getAssociatedTribeAccount ${mentionedGithubUser})
+              [ -z "${response}" ] && continue
+              [ -z "${mentionedServerUsers}" ] && mentionedServerUsers="@${response}" || mentionedServerUsers="${mentionedServerUsers} and @${response}"
+            done
+            [ -z "${mentionedServerUsers}" ] && mentionedServerUsers="$(echo $mentionedGithubUsers | wc -w ) user(s)"
+            msg="🙋 $link has ${mentionEventLink} ${mentionedServerUsers} in a comment."
           else
             stateEventLink="<a href=\"$reviewEventLink\">${{ github.event.review.state }}</a>"
             msg="ℹ️ $link has been ${stateEventLink}."
@@ -92,6 +138,7 @@ runs:
         SERVER_USERNAME: ${{ inputs.SERVER_USERNAME }}
         SERVER_PASSWORD: ${{ inputs.SERVER_PASSWORD }}
         SERVER_TASK_REST_PREFIXE_URL: ${{ inputs.SERVER_URL }}/rest/private/tasks
+        SERVER_GAMGH_MAPPING_FILE_URL: ${{ inputs.SERVER_URL }}/rest/jcr/repository/collaboration/Users/g___/gi___/git___/githubagent/Public/ghtribe.json
         TASKS_REGEX_FILTER: ${{ inputs.TASKS_REGEX_FILTER }}
         SERVER_DEFAULT_SITENAME: ${{ inputs.SERVER_DEFAULT_SITENAME }}
         message: ${{ github.event.pull_request.title }}
